http:
  routers:
    esportnews-backend:
      rule: "(Host(`esportnews.fr`) || Host(`www.esportnews.fr`)) && (PathPrefix(`/api/`) || Path(`/api`) || Path(`/health`))"
      service: esportnews-backend
      entryPoints:
        - websecure
      priority: 1000
      tls:
        certResolver: letsencrypt

  services:
    esportnews-backend:
      loadBalancer:
        servers:
          - url: "http://esportnews-backend-prod:4000"
