-- Migration: Create page_views table for analytics
-- Description: Track anonymous visitor page views for analytics dashboard
-- Retention: Unlimited (no auto-cleanup)

CREATE TABLE IF NOT EXISTS page_views (
    id BIGSERIAL PRIMARY KEY,
    visitor_id UUID NOT NULL, -- Anonymous visitor identifier (generated frontend)
    user_id BIGINT NULL, -- Logged-in user ID (optional, FK to users)
    path TEXT NOT NULL, -- URL path: /article/slug, /tournaments, etc.
    referer TEXT, -- HTTP referer header
    user_agent TEXT, -- User agent string
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_page_views_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE SET NULL
);

-- Indexes for performance (queries by timeline)
CREATE INDEX IF NOT EXISTS idx_page_views_visitor_id ON page_views (visitor_id);

CREATE INDEX IF NOT EXISTS idx_page_views_user_id ON page_views (user_id)
WHERE
    user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_page_views_created_at ON page_views (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_page_views_path ON page_views (path);

-- Composite index for common analytics queries
CREATE INDEX IF NOT EXISTS idx_page_views_visitor_created ON page_views (visitor_id, created_at DESC);

-- Comment
COMMENT ON
TABLE page_views IS 'Analytics tracking - page views for visitor statistics';

COMMENT ON COLUMN page_views.visitor_id IS 'Anonymous UUID generated by frontend (localStorage)';

COMMENT ON COLUMN page_views.user_id IS 'Optional link to authenticated user (NULL for anonymous visitors)';

COMMENT ON COLUMN page_views.path IS 'URL pathname (e.g. /article/valorant-championship-2025)';